#!/bin/bash
# Parameters Order
# $1 DATE, $2 DOWN, $3UP and $4 Ping

load_config()
{
	source /opt/speedflow/config
}

run_api_call()
{

STATUS=$(
	curl --include \
	--request POST \
	--header "Content-Type: application/json" \
	--data-binary "[
	{
	\"date\" :\"$1\",
	\"download\" :$2,
	\"upload\" :$3,
	\"ping\" :$4
	}
	]" \
	-s -o /dev/null -w '%{http_code}' \
	"$REST_PBI"
)
	
	export TZ=$TZONE	
	NOW=$(date)
	echo "$NOW - API CALL HTTP STATUS:$STATUS" >> $LOG_DIR/$LOG_NAME
	if [ $STATUS -eq 200 ];then 
		echo "$NOW - $1 $2 $3 $4 data sent sucessfully" >> $LOG_DIR/$LOG_NAME
	else
		echo "$NOW - Something went wrong ($STATUS). Please debug api call manualy using curl" >> $LOG_DIR/$LOG_NAME
	fi

}

load_config
run_api_call $1 $2 $3 $4
