#!/bin/bash

load_config()
{
source /opt/speedflow/config
}

dep_check()
{
#This is a simple test to check this script dependencies.

if ! [ -x "$(command -v $1)" ]; then
  echo "Error: $1 is not installed. Try apt-get install $1." >&2
  exit 1
fi

if ! [ -x "$(command -v $2)" ]; then
  echo "Error: $2 is not installed. Try apt-get install $2." >&2
  exit 1
fi

}

run_speedtest()
{
#Check tmp directory

if [ ! -d "$TMP_DIR" ]; then
	mkdir $TMP_DIR
fi

#Run Speedtest and colect values
speedtest --secure --simple > $TMP_DIR/.collector
if [ $? -eq 0 ]
then
#Parse Results
	PING=$(cat $TMP_DIR/.collector | grep ping -i | cut -d" " -f2)
	DOWN=$(cat $TMP_DIR/.collector | grep down -i | cut -d" " -f2)
	UP=$(cat $TMP_DIR/.collector | grep up -i | cut -d" " -f2)
fi
}

logger()
{
	NOW=$(date -u)
	if [ ! -d "$LOG_DIR" ]; then
		mkdir $LOG_DIR
	fi	
	echo "$NOW - Ping:$PING DOWNLOAD:$DOWN UPLOAD:$UP" >> $LOG_DIR/speedflow.log
}

load_config
dep_check speedtest curl
run_speedtest
logger
